---
- name: Start service (command)
  shell: "{{ command }}"
  when: command is defined

- name: Start service (service command)
  service:
    name: "{{ service_name }}"
    state: started
    enabled: yes
  when: service_name is defined
