AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 8

Metrics/BlockLength:
  Exclude:
    - 'vultest.rb'
    - 'simple_vultest.rb'