---
- name: "gem install {{ name }} -v {{ version }}"
  gem:
    name: "{{ name }}"
    version: "{{ version }}"
    executable: "{{ executable }}"
    user_install: no
    state: present
  become_user: "{{ user }}"
