---
- name: Dockerfile用のディレクトリを作成
  file:
    path: "{{src_dir}}/docker"
    state: directory
    mode: 0755

- name: ベースイメージ用のディレクトリを作成
  file:
    path: "{{src_dir}}/docker/CentOS"
    state: directory
    mode: 0755
- name: ベースイメージを作成するためのファイルをコピー
  copy:
    src: ../files/CentOS/centos-64.tar.xz
    dest: "{{src_dir}}/docker/CentOS"
    mode: 0755
    owner: root
    group: root
- name: ベースイメージ を作成するためのシェルをコピー
  copy:
    src: ../files/CentOS/make.sh
    dest: "{{src_dir}}/docker/CentOS"
    mode: 0755
    owner: root
    group: root
- name: "{{centos_version}}のベースイメージを作成"
  command: "./make.sh"
  args:
    chdir: "{{src_dir}}/docker/CentOS"

- name: apacheの設定ファイルのディレクトリを作成
  file:
    path: "{{src_dir}}/docker/apache/conf"
    state: directory
    mode: 0755
- name: apacheの設定ファイルをコピー
  copy:
    src: ../files/apache/conf/httpd.conf
    dest: "{{src_dir}}/docker/apache/conf"
    mode: 0755
    owner: root
    group: root

- name: cgiファイルのディレクトリを作成
  file:
    path: "{{src_dir}}/docker/cgi-bin"
    state: directory
    mode: 0755
- name: cgiファイルの設定ファイルをコピー
  copy:
    src: ../files/shellshock/cgi-bin/shellshock.cgi
    dest: "{{src_dir}}/docker/cgi-bin"
    mode: 0755
    owner: root
    group: root

- name: docker-composeファイルのコピー
  copy:
    src: ../files/shellshock/docker/docker-compose.yml
    dest: "{{src_dir}}/docker"
    mode: 0755
    owner: root
    group: root
- name: dockerファイルのコピー
  copy:
    src: ../files/shellshock/docker/apache/Dockerfile
    dest: "{{src_dir}}/docker/apache"
    mode: 0755
    owner: root
    group: root

