cve: CVE-2017-7308
attack_vector: local

os:
  name: ubuntu
  version: 16.04.1
software:
  - name: linux_image_version_generic
    version: 4.8.0-41-generic
    os_depend: true
    affect_kernel: true
caution:
  - type: reload
    msg: at least two CPU cores.
