cve: CVE-2017-16995

os:
  name: ubuntu
  version: 16.04.2
software:
  - name: linux_image_version_generic
    package: 
      - name: linux_image_version_generic
        version: 4.4.0-89-generic
    os_depend: true
    vars_file_exit: true
  - name: libfuse-dev
    os_depend: true
    vars_file_exit: false
  - name: pkg-config
    os_depend: true
    vars_file_exit: false
