cve: CVE-2015-1328
attack_vector: local

os:
  name: ubuntu
  version: 14.04.0
software:
  - name: linux_image_version_generic
    version: 3.13.0-24-generic
    configure_command: false
    os_depend: true
setting: false
