cve: CVE-2017-16995
attack_vector: local

os:
  name: ubuntu
  version: 16.04.2
software:
  - name: linux_image_version_generic
    version: 4.4.0-89-generic
    os_depend: true
    affect_kernel: version
  - name: libfuse-dev
    os_depend: true
  - name: pkg-config
    os_depend: true
