cve: CVE-2017-1000113
attack_vector: local

os:
  name: ubuntu
  version: 16.04.1
software:
  - name: linux_image_version_generic
    version: 4.4.0-81-generic
    os_depend: true
    affect_kernel: true
setting: setting/CVE-2018-10900/default
