cve: CVE-2016-4997

os:
  name: ubuntu
  version: 16.04.1
software:
  - name: linux_image_version_generic
    package: 
      - name: linux_image_version_generic
        version: 4.4.0-21-generic
    os_depend: true
    version_depend: true
    vars_file_exit: true
  - name: libfuse-dev
    os_depend: true
    version_depend: false
    vars_file_exit: false
  - name: pkg-config
    os_depend: true
    version_depend: false
    vars_file_exit: false
