cve: CVE-2015-1328

os:
  name: ubuntu
  version: 14.04.0
software:
  - name: linux_image_version_generic
    package:
      - name: linux_image_version_generic
        version: 3.13.0-24-generic
    os_depend: true
    vars_file_exit: true
