---
- name: apacheに必要なツールのダウンロード
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - gcc
    - make
    - pcre
    - pcre-devel
    - wget
    - zlib-devel
    - openssl-devel
    - expat-devel

- name: APRをダウンロード
  get_url:
    url: http://ftp.yz.yamagata-u.ac.jp/pub/network/apache//apr/apr-{{apr_version}}.tar.gz
    dest: "{{src_dir}}/apr-{{apr_version}}.tar.gz"
- name: APRのファイルを展開
  unarchive:
    src: "{{src_dir}}/apr-{{apr_version}}.tar.gz"
    dest: "{{src_dir}}"
    remote_src: yes
- name: APRのconfigfileを実行
  command:
    ./configure --prefix=/opt/apr/apr-{{apr_version}}
  args:
    chdir: "{{src_dir}}/apr-{{apr_version}}"
- name: APRのmakeを実行
  make:
    chdir: "{{src_dir}}/apr-{{apr_version}}"
- name: APRのmake insatallを実行
  make:
    chdir: "{{src_dir}}/apr-{{apr_version}}"
    target: install

- name: APR-utilをダウンロード
  get_url:
    url: http://ftp.jaist.ac.jp/pub/apache//apr/apr-util-{{apr_util_version}}.tar.gz
    dest: "{{src_dir}}/apr-util-{{apr_util_version}}.tar.gz"
- name: APR-utilのファイルを展開
  unarchive:
    src: "{{src_dir}}/apr-util-{{apr_util_version}}.tar.gz"
    dest: "{{src_dir}}"
    remote_src: yes
- name: APR-utilのconfigfileを実行
  command:
    ./configure --prefix=/opt/apr-util/apr-util-{{apr_util_version}} --with-apr=/opt/apr/apr-{{apr_version}}
  args:
    chdir: "{{src_dir}}/apr-util-{{apr_util_version}}"
- name: APR-utilのmakeを実行
  make:
    chdir: "{{src_dir}}/apr-util-{{apr_util_version}}"
- name: APR-utilのmake installを実行
  make:
    chdir: "{{src_dir}}/apr-util-{{apr_util_version}}"
    target: install

- name: httpdをダウンロード
  get_url:
    url: http://ftp.jaist.ac.jp/pub/apache//httpd/httpd-{{httpd_version}}.tar.gz
    dest: "{{src_dir}}/httpd-{{httpd_version}}.tar.gz"
- name: httpdのファイルを展開
  unarchive:
    src: "{{src_dir}}/httpd-{{httpd_version}}.tar.gz"
    dest: "{{src_dir}}"
    remote_src: yes
- name: httpdのconfigfileを実行
  command:
    ./configure --prefix=/opt/httpd/httpd-{{httpd_version}} --with-apr=/opt/apr/apr-{{apr_version}} --with-apr-util=/opt/apr-util/apr-util-{{apr_util_version}} --enable-module=all --enable-so --with-openssl
  args:
    chdir: "{{src_dir}}/httpd-{{httpd_version}}"
- name: httpdのmakeを実行
  make:
    chdir: "{{src_dir}}/httpd-{{httpd_version}}"
- name: httpdのmake installを実行
  make:
    chdir: "{{src_dir}}/httpd-{{httpd_version}}"
    target: install

