---
- name: Exit rails app?
  stat:
    path: /home/rails/taco
  register: app
- name: rails new taco
  shell: bash -lc "rails new taco"
  args:
    chdir: /home/rails
  become_user: rails
  when: not app.stat.exists
- name: "Input config.web_console.whitelisted_ips = %w(0.0.0.0/0) in /home/rails/taco/config/environments/development.rb"
  replace:
    path: /home/rails/taco/config/environments/development.rb
    regexp: '^end$'
    replace: "  config.web_console.whitelisted_ips = %w(0.0.0.0/0)\nend "
  become_user: rails
  when: not app.stat.exists
- name: command bundle
  shell: bash -lc "bundle"
  args:
    chdir: /home/rails/taco
  become_user: rails
  when: not app.stat.exists
- name: rails s -b 192.168.33.10
  shell: bash -lc "rails s -d -b 192.168.33.10"
  args:
    chdir: /home/rails/taco
  become_user: rails
